// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IdentityProvider struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityProvider) Reset()         { *m = IdentityProvider{} }
func (m *IdentityProvider) String() string { return proto.CompactTextString(m) }
func (*IdentityProvider) ProtoMessage()    {}
func (*IdentityProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{0}
}
func (m *IdentityProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityProvider.Unmarshal(m, b)
}
func (m *IdentityProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityProvider.Marshal(b, m, deterministic)
}
func (dst *IdentityProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityProvider.Merge(dst, src)
}
func (m *IdentityProvider) XXX_Size() int {
	return xxx_messageInfo_IdentityProvider.Size(m)
}
func (m *IdentityProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityProvider.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityProvider proto.InternalMessageInfo

func (m *IdentityProvider) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *IdentityProvider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListIdentityProvidersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIdentityProvidersRequest) Reset()         { *m = ListIdentityProvidersRequest{} }
func (m *ListIdentityProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*ListIdentityProvidersRequest) ProtoMessage()    {}
func (*ListIdentityProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{1}
}
func (m *ListIdentityProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIdentityProvidersRequest.Unmarshal(m, b)
}
func (m *ListIdentityProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIdentityProvidersRequest.Marshal(b, m, deterministic)
}
func (dst *ListIdentityProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIdentityProvidersRequest.Merge(dst, src)
}
func (m *ListIdentityProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_ListIdentityProvidersRequest.Size(m)
}
func (m *ListIdentityProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIdentityProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIdentityProvidersRequest proto.InternalMessageInfo

type ListIdentityProvidersResponse struct {
	IdentityProviders    []*IdentityProvider `protobuf:"bytes,1,rep,name=identityProviders,proto3" json:"identityProviders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListIdentityProvidersResponse) Reset()         { *m = ListIdentityProvidersResponse{} }
func (m *ListIdentityProvidersResponse) String() string { return proto.CompactTextString(m) }
func (*ListIdentityProvidersResponse) ProtoMessage()    {}
func (*ListIdentityProvidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{2}
}
func (m *ListIdentityProvidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIdentityProvidersResponse.Unmarshal(m, b)
}
func (m *ListIdentityProvidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIdentityProvidersResponse.Marshal(b, m, deterministic)
}
func (dst *ListIdentityProvidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIdentityProvidersResponse.Merge(dst, src)
}
func (m *ListIdentityProvidersResponse) XXX_Size() int {
	return xxx_messageInfo_ListIdentityProvidersResponse.Size(m)
}
func (m *ListIdentityProvidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIdentityProvidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListIdentityProvidersResponse proto.InternalMessageInfo

func (m *ListIdentityProvidersResponse) GetIdentityProviders() []*IdentityProvider {
	if m != nil {
		return m.IdentityProviders
	}
	return nil
}

type AddIdentityProviderRequest struct {
	IdentityProviderUrl  string   `protobuf:"bytes,1,opt,name=identityProviderUrl,proto3" json:"identityProviderUrl,omitempty"`
	EmailOrPhone         string   `protobuf:"bytes,2,opt,name=emailOrPhone,proto3" json:"emailOrPhone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIdentityProviderRequest) Reset()         { *m = AddIdentityProviderRequest{} }
func (m *AddIdentityProviderRequest) String() string { return proto.CompactTextString(m) }
func (*AddIdentityProviderRequest) ProtoMessage()    {}
func (*AddIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{3}
}
func (m *AddIdentityProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIdentityProviderRequest.Unmarshal(m, b)
}
func (m *AddIdentityProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIdentityProviderRequest.Marshal(b, m, deterministic)
}
func (dst *AddIdentityProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIdentityProviderRequest.Merge(dst, src)
}
func (m *AddIdentityProviderRequest) XXX_Size() int {
	return xxx_messageInfo_AddIdentityProviderRequest.Size(m)
}
func (m *AddIdentityProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIdentityProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddIdentityProviderRequest proto.InternalMessageInfo

func (m *AddIdentityProviderRequest) GetIdentityProviderUrl() string {
	if m != nil {
		return m.IdentityProviderUrl
	}
	return ""
}

func (m *AddIdentityProviderRequest) GetEmailOrPhone() string {
	if m != nil {
		return m.EmailOrPhone
	}
	return ""
}

type AddIdentityProviderResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	IdentityProviderId   string   `protobuf:"bytes,2,opt,name=identityProviderId,proto3" json:"identityProviderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIdentityProviderResponse) Reset()         { *m = AddIdentityProviderResponse{} }
func (m *AddIdentityProviderResponse) String() string { return proto.CompactTextString(m) }
func (*AddIdentityProviderResponse) ProtoMessage()    {}
func (*AddIdentityProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{4}
}
func (m *AddIdentityProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIdentityProviderResponse.Unmarshal(m, b)
}
func (m *AddIdentityProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIdentityProviderResponse.Marshal(b, m, deterministic)
}
func (dst *AddIdentityProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIdentityProviderResponse.Merge(dst, src)
}
func (m *AddIdentityProviderResponse) XXX_Size() int {
	return xxx_messageInfo_AddIdentityProviderResponse.Size(m)
}
func (m *AddIdentityProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIdentityProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddIdentityProviderResponse proto.InternalMessageInfo

func (m *AddIdentityProviderResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *AddIdentityProviderResponse) GetIdentityProviderId() string {
	if m != nil {
		return m.IdentityProviderId
	}
	return ""
}

type ConfirmIdentityProviderRequest struct {
	IdentityProviderUrl  string   `protobuf:"bytes,1,opt,name=identityProviderUrl,proto3" json:"identityProviderUrl,omitempty"`
	IdentityProviderId   string   `protobuf:"bytes,2,opt,name=identityProviderId,proto3" json:"identityProviderId,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,3,opt,name=confirmationCode,proto3" json:"confirmationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmIdentityProviderRequest) Reset()         { *m = ConfirmIdentityProviderRequest{} }
func (m *ConfirmIdentityProviderRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmIdentityProviderRequest) ProtoMessage()    {}
func (*ConfirmIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{5}
}
func (m *ConfirmIdentityProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmIdentityProviderRequest.Unmarshal(m, b)
}
func (m *ConfirmIdentityProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmIdentityProviderRequest.Marshal(b, m, deterministic)
}
func (dst *ConfirmIdentityProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmIdentityProviderRequest.Merge(dst, src)
}
func (m *ConfirmIdentityProviderRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmIdentityProviderRequest.Size(m)
}
func (m *ConfirmIdentityProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmIdentityProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmIdentityProviderRequest proto.InternalMessageInfo

func (m *ConfirmIdentityProviderRequest) GetIdentityProviderUrl() string {
	if m != nil {
		return m.IdentityProviderUrl
	}
	return ""
}

func (m *ConfirmIdentityProviderRequest) GetIdentityProviderId() string {
	if m != nil {
		return m.IdentityProviderId
	}
	return ""
}

func (m *ConfirmIdentityProviderRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

type ConfirmIdentityProviderResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmIdentityProviderResponse) Reset()         { *m = ConfirmIdentityProviderResponse{} }
func (m *ConfirmIdentityProviderResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmIdentityProviderResponse) ProtoMessage()    {}
func (*ConfirmIdentityProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{6}
}
func (m *ConfirmIdentityProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmIdentityProviderResponse.Unmarshal(m, b)
}
func (m *ConfirmIdentityProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmIdentityProviderResponse.Marshal(b, m, deterministic)
}
func (dst *ConfirmIdentityProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmIdentityProviderResponse.Merge(dst, src)
}
func (m *ConfirmIdentityProviderResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmIdentityProviderResponse.Size(m)
}
func (m *ConfirmIdentityProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmIdentityProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmIdentityProviderResponse proto.InternalMessageInfo

func (m *ConfirmIdentityProviderResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type RegisterDeviceRequest struct {
	DevID                string   `protobuf:"bytes,1,opt,name=devID,proto3" json:"devID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceRequest) Reset()         { *m = RegisterDeviceRequest{} }
func (m *RegisterDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceRequest) ProtoMessage()    {}
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{7}
}
func (m *RegisterDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceRequest.Unmarshal(m, b)
}
func (m *RegisterDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceRequest.Merge(dst, src)
}
func (m *RegisterDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceRequest.Size(m)
}
func (m *RegisterDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceRequest proto.InternalMessageInfo

func (m *RegisterDeviceRequest) GetDevID() string {
	if m != nil {
		return m.DevID
	}
	return ""
}

type RegisterDeviceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterDeviceResponse) Reset()         { *m = RegisterDeviceResponse{} }
func (m *RegisterDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterDeviceResponse) ProtoMessage()    {}
func (*RegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{8}
}
func (m *RegisterDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterDeviceResponse.Unmarshal(m, b)
}
func (m *RegisterDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterDeviceResponse.Marshal(b, m, deterministic)
}
func (dst *RegisterDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterDeviceResponse.Merge(dst, src)
}
func (m *RegisterDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterDeviceResponse.Size(m)
}
func (m *RegisterDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterDeviceResponse proto.InternalMessageInfo

type ListNonRegisteredDevicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNonRegisteredDevicesRequest) Reset()         { *m = ListNonRegisteredDevicesRequest{} }
func (m *ListNonRegisteredDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListNonRegisteredDevicesRequest) ProtoMessage()    {}
func (*ListNonRegisteredDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{9}
}
func (m *ListNonRegisteredDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNonRegisteredDevicesRequest.Unmarshal(m, b)
}
func (m *ListNonRegisteredDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNonRegisteredDevicesRequest.Marshal(b, m, deterministic)
}
func (dst *ListNonRegisteredDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNonRegisteredDevicesRequest.Merge(dst, src)
}
func (m *ListNonRegisteredDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListNonRegisteredDevicesRequest.Size(m)
}
func (m *ListNonRegisteredDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNonRegisteredDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNonRegisteredDevicesRequest proto.InternalMessageInfo

type ListNonRegisteredDevicesResponse struct {
	Devices              []string `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListNonRegisteredDevicesResponse) Reset()         { *m = ListNonRegisteredDevicesResponse{} }
func (m *ListNonRegisteredDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListNonRegisteredDevicesResponse) ProtoMessage()    {}
func (*ListNonRegisteredDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{10}
}
func (m *ListNonRegisteredDevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNonRegisteredDevicesResponse.Unmarshal(m, b)
}
func (m *ListNonRegisteredDevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNonRegisteredDevicesResponse.Marshal(b, m, deterministic)
}
func (dst *ListNonRegisteredDevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNonRegisteredDevicesResponse.Merge(dst, src)
}
func (m *ListNonRegisteredDevicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListNonRegisteredDevicesResponse.Size(m)
}
func (m *ListNonRegisteredDevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNonRegisteredDevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNonRegisteredDevicesResponse proto.InternalMessageInfo

func (m *ListNonRegisteredDevicesResponse) GetDevices() []string {
	if m != nil {
		return m.Devices
	}
	return nil
}

type AddWalletRequest struct {
	QRcode               string   `protobuf:"bytes,1,opt,name=QRcode,proto3" json:"QRcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWalletRequest) Reset()         { *m = AddWalletRequest{} }
func (m *AddWalletRequest) String() string { return proto.CompactTextString(m) }
func (*AddWalletRequest) ProtoMessage()    {}
func (*AddWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{11}
}
func (m *AddWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWalletRequest.Unmarshal(m, b)
}
func (m *AddWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWalletRequest.Marshal(b, m, deterministic)
}
func (dst *AddWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWalletRequest.Merge(dst, src)
}
func (m *AddWalletRequest) XXX_Size() int {
	return xxx_messageInfo_AddWalletRequest.Size(m)
}
func (m *AddWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWalletRequest proto.InternalMessageInfo

func (m *AddWalletRequest) GetQRcode() string {
	if m != nil {
		return m.QRcode
	}
	return ""
}

type AddWalletResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWalletResponse) Reset()         { *m = AddWalletResponse{} }
func (m *AddWalletResponse) String() string { return proto.CompactTextString(m) }
func (*AddWalletResponse) ProtoMessage()    {}
func (*AddWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_ce49df1ceb7ee97d, []int{12}
}
func (m *AddWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWalletResponse.Unmarshal(m, b)
}
func (m *AddWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWalletResponse.Marshal(b, m, deterministic)
}
func (dst *AddWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWalletResponse.Merge(dst, src)
}
func (m *AddWalletResponse) XXX_Size() int {
	return xxx_messageInfo_AddWalletResponse.Size(m)
}
func (m *AddWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddWalletResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IdentityProvider)(nil), "api.IdentityProvider")
	proto.RegisterType((*ListIdentityProvidersRequest)(nil), "api.ListIdentityProvidersRequest")
	proto.RegisterType((*ListIdentityProvidersResponse)(nil), "api.ListIdentityProvidersResponse")
	proto.RegisterType((*AddIdentityProviderRequest)(nil), "api.AddIdentityProviderRequest")
	proto.RegisterType((*AddIdentityProviderResponse)(nil), "api.AddIdentityProviderResponse")
	proto.RegisterType((*ConfirmIdentityProviderRequest)(nil), "api.ConfirmIdentityProviderRequest")
	proto.RegisterType((*ConfirmIdentityProviderResponse)(nil), "api.ConfirmIdentityProviderResponse")
	proto.RegisterType((*RegisterDeviceRequest)(nil), "api.RegisterDeviceRequest")
	proto.RegisterType((*RegisterDeviceResponse)(nil), "api.RegisterDeviceResponse")
	proto.RegisterType((*ListNonRegisteredDevicesRequest)(nil), "api.ListNonRegisteredDevicesRequest")
	proto.RegisterType((*ListNonRegisteredDevicesResponse)(nil), "api.ListNonRegisteredDevicesResponse")
	proto.RegisterType((*AddWalletRequest)(nil), "api.AddWalletRequest")
	proto.RegisterType((*AddWalletResponse)(nil), "api.AddWalletResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeneratorAdminClient is the client API for GeneratorAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeneratorAdminClient interface {
	ListIdentityProviders(ctx context.Context, in *ListIdentityProvidersRequest, opts ...grpc.CallOption) (*ListIdentityProvidersResponse, error)
	AddIdentityProvider(ctx context.Context, in *AddIdentityProviderRequest, opts ...grpc.CallOption) (*AddIdentityProviderResponse, error)
	ConfirmIdentityProvider(ctx context.Context, in *ConfirmIdentityProviderRequest, opts ...grpc.CallOption) (*ConfirmIdentityProviderResponse, error)
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	ListNonRegisteredDevices(ctx context.Context, in *ListNonRegisteredDevicesRequest, opts ...grpc.CallOption) (*ListNonRegisteredDevicesResponse, error)
	AddWallet(ctx context.Context, in *AddWalletRequest, opts ...grpc.CallOption) (*AddWalletResponse, error)
}

type generatorAdminClient struct {
	cc *grpc.ClientConn
}

func NewGeneratorAdminClient(cc *grpc.ClientConn) GeneratorAdminClient {
	return &generatorAdminClient{cc}
}

func (c *generatorAdminClient) ListIdentityProviders(ctx context.Context, in *ListIdentityProvidersRequest, opts ...grpc.CallOption) (*ListIdentityProvidersResponse, error) {
	out := new(ListIdentityProvidersResponse)
	err := c.cc.Invoke(ctx, "/api.GeneratorAdmin/listIdentityProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorAdminClient) AddIdentityProvider(ctx context.Context, in *AddIdentityProviderRequest, opts ...grpc.CallOption) (*AddIdentityProviderResponse, error) {
	out := new(AddIdentityProviderResponse)
	err := c.cc.Invoke(ctx, "/api.GeneratorAdmin/addIdentityProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorAdminClient) ConfirmIdentityProvider(ctx context.Context, in *ConfirmIdentityProviderRequest, opts ...grpc.CallOption) (*ConfirmIdentityProviderResponse, error) {
	out := new(ConfirmIdentityProviderResponse)
	err := c.cc.Invoke(ctx, "/api.GeneratorAdmin/confirmIdentityProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorAdminClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.GeneratorAdmin/registerDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorAdminClient) ListNonRegisteredDevices(ctx context.Context, in *ListNonRegisteredDevicesRequest, opts ...grpc.CallOption) (*ListNonRegisteredDevicesResponse, error) {
	out := new(ListNonRegisteredDevicesResponse)
	err := c.cc.Invoke(ctx, "/api.GeneratorAdmin/listNonRegisteredDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generatorAdminClient) AddWallet(ctx context.Context, in *AddWalletRequest, opts ...grpc.CallOption) (*AddWalletResponse, error) {
	out := new(AddWalletResponse)
	err := c.cc.Invoke(ctx, "/api.GeneratorAdmin/addWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratorAdminServer is the server API for GeneratorAdmin service.
type GeneratorAdminServer interface {
	ListIdentityProviders(context.Context, *ListIdentityProvidersRequest) (*ListIdentityProvidersResponse, error)
	AddIdentityProvider(context.Context, *AddIdentityProviderRequest) (*AddIdentityProviderResponse, error)
	ConfirmIdentityProvider(context.Context, *ConfirmIdentityProviderRequest) (*ConfirmIdentityProviderResponse, error)
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	ListNonRegisteredDevices(context.Context, *ListNonRegisteredDevicesRequest) (*ListNonRegisteredDevicesResponse, error)
	AddWallet(context.Context, *AddWalletRequest) (*AddWalletResponse, error)
}

func RegisterGeneratorAdminServer(s *grpc.Server, srv GeneratorAdminServer) {
	s.RegisterService(&_GeneratorAdmin_serviceDesc, srv)
}

func _GeneratorAdmin_ListIdentityProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentityProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAdminServer).ListIdentityProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GeneratorAdmin/ListIdentityProviders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAdminServer).ListIdentityProviders(ctx, req.(*ListIdentityProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneratorAdmin_AddIdentityProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIdentityProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAdminServer).AddIdentityProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GeneratorAdmin/AddIdentityProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAdminServer).AddIdentityProvider(ctx, req.(*AddIdentityProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneratorAdmin_ConfirmIdentityProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmIdentityProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAdminServer).ConfirmIdentityProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GeneratorAdmin/ConfirmIdentityProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAdminServer).ConfirmIdentityProvider(ctx, req.(*ConfirmIdentityProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneratorAdmin_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAdminServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GeneratorAdmin/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAdminServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneratorAdmin_ListNonRegisteredDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNonRegisteredDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAdminServer).ListNonRegisteredDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GeneratorAdmin/ListNonRegisteredDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAdminServer).ListNonRegisteredDevices(ctx, req.(*ListNonRegisteredDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneratorAdmin_AddWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorAdminServer).AddWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GeneratorAdmin/AddWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorAdminServer).AddWallet(ctx, req.(*AddWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeneratorAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GeneratorAdmin",
	HandlerType: (*GeneratorAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listIdentityProviders",
			Handler:    _GeneratorAdmin_ListIdentityProviders_Handler,
		},
		{
			MethodName: "addIdentityProvider",
			Handler:    _GeneratorAdmin_AddIdentityProvider_Handler,
		},
		{
			MethodName: "confirmIdentityProvider",
			Handler:    _GeneratorAdmin_ConfirmIdentityProvider_Handler,
		},
		{
			MethodName: "registerDevice",
			Handler:    _GeneratorAdmin_RegisterDevice_Handler,
		},
		{
			MethodName: "listNonRegisteredDevices",
			Handler:    _GeneratorAdmin_ListNonRegisteredDevices_Handler,
		},
		{
			MethodName: "addWallet",
			Handler:    _GeneratorAdmin_AddWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_ce49df1ceb7ee97d) }

var fileDescriptor_api_ce49df1ceb7ee97d = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x26, 0x89, 0x56, 0x73, 0x94, 0x90, 0x4e, 0x4c, 0x5c, 0xa6, 0xb5, 0x49, 0xc7, 0x0a, 0xa5,
	0x60, 0x2a, 0xd5, 0x2b, 0xd1, 0x8b, 0x90, 0x82, 0x04, 0x44, 0xeb, 0x82, 0xe8, 0x95, 0x30, 0x66,
	0x8e, 0x71, 0x60, 0x33, 0xb3, 0xce, 0x4e, 0x03, 0xbe, 0x8d, 0x4f, 0xe0, 0x33, 0x4a, 0x66, 0x66,
	0x83, 0xd9, 0xec, 0x6e, 0x11, 0xbc, 0xdb, 0x39, 0xe7, 0xfb, 0xce, 0xef, 0x77, 0x16, 0xda, 0x3c,
	0x95, 0xe3, 0xd4, 0x68, 0xab, 0x49, 0x8b, 0xa7, 0x92, 0x1e, 0x2e, 0xb4, 0x5e, 0x24, 0x78, 0xce,
	0x53, 0x79, 0xce, 0x95, 0xd2, 0x96, 0x5b, 0xa9, 0x55, 0xe6, 0x21, 0xec, 0x05, 0x74, 0x67, 0x02,
	0x95, 0x95, 0xf6, 0xe7, 0x95, 0xd1, 0x2b, 0x29, 0xd0, 0x90, 0x2e, 0xb4, 0xae, 0x4d, 0x12, 0x35,
	0x46, 0x8d, 0xd3, 0x76, 0xbc, 0xfe, 0x24, 0x1d, 0x68, 0x4a, 0x11, 0x35, 0x9d, 0xa1, 0x29, 0x05,
	0x3b, 0x82, 0xc3, 0xb7, 0x32, 0xb3, 0x45, 0x66, 0x16, 0xe3, 0x8f, 0x6b, 0xcc, 0x2c, 0x13, 0xf0,
	0xa8, 0xc2, 0x9f, 0xa5, 0x5a, 0x65, 0x48, 0xa6, 0xb0, 0x2f, 0x8b, 0xce, 0xa8, 0x31, 0x6a, 0x9d,
	0xde, 0xbb, 0xe8, 0x8f, 0xd7, 0x0d, 0x14, 0xa9, 0xf1, 0x2e, 0x9e, 0x19, 0xa0, 0x13, 0x21, 0x76,
	0x90, 0xbe, 0x06, 0xf2, 0x0c, 0x7a, 0x45, 0xca, 0xc7, 0x4d, 0x57, 0x65, 0x2e, 0xc2, 0xe0, 0x3e,
	0x2e, 0xb9, 0x4c, 0xde, 0x9b, 0xab, 0xef, 0x5a, 0x61, 0xe8, 0x77, 0xcb, 0xc6, 0x24, 0x1c, 0x94,
	0xe6, 0x0c, 0x7d, 0x51, 0xb8, 0x6b, 0xc2, 0x77, 0xc8, 0xb4, 0x79, 0x93, 0x31, 0x90, 0x62, 0xd6,
	0x59, 0x3e, 0xd4, 0x12, 0x0f, 0xfb, 0xdd, 0x80, 0xa3, 0xa9, 0x56, 0xdf, 0xa4, 0x59, 0xfe, 0xbf,
	0x1e, 0xff, 0xb1, 0x08, 0x72, 0x06, 0xdd, 0xb9, 0xaf, 0xc1, 0xc9, 0x66, 0xaa, 0x05, 0x46, 0x2d,
	0x87, 0xde, 0xb1, 0xb3, 0xd7, 0x30, 0xac, 0xac, 0xf7, 0xe6, 0xf9, 0xb0, 0xa7, 0xd0, 0x8f, 0x71,
	0x21, 0x33, 0x8b, 0xe6, 0x12, 0x57, 0x72, 0x8e, 0x79, 0x97, 0x0f, 0xe0, 0xb6, 0xc0, 0xd5, 0xec,
	0x32, 0x30, 0xfc, 0x83, 0x45, 0x30, 0x28, 0xc2, 0x43, 0xa0, 0x63, 0x18, 0xae, 0xd5, 0xf7, 0x4e,
	0xab, 0x1c, 0x80, 0xc2, 0x43, 0x36, 0x02, 0x7d, 0x05, 0xa3, 0x6a, 0x48, 0xa8, 0x35, 0x82, 0x3b,
	0xc2, 0x9b, 0x9c, 0x32, 0xdb, 0x71, 0xfe, 0x64, 0x67, 0xd0, 0x9d, 0x08, 0xf1, 0x89, 0x27, 0x09,
	0xda, 0xbc, 0xc8, 0x01, 0xec, 0x7d, 0x88, 0xe7, 0xeb, 0xf1, 0xf8, 0x2a, 0xc3, 0x8b, 0xf5, 0x60,
	0xff, 0x2f, 0xac, 0x0f, 0x7d, 0xf1, 0xeb, 0x16, 0x74, 0xde, 0xa0, 0x42, 0xc3, 0xad, 0x36, 0x13,
	0xb1, 0x94, 0x8a, 0x7c, 0x81, 0x7e, 0x52, 0x76, 0x32, 0xe4, 0xd8, 0xdd, 0x43, 0xdd, 0xb9, 0x51,
	0x56, 0x07, 0x09, 0xdd, 0x7c, 0x86, 0x1e, 0xdf, 0x15, 0x2e, 0x19, 0x3a, 0x6a, 0xf5, 0x19, 0xd1,
	0x51, 0x35, 0x20, 0x44, 0x16, 0xf0, 0x70, 0x5e, 0xbe, 0x76, 0xf2, 0xd8, 0x91, 0xeb, 0x45, 0x4c,
	0x4f, 0xea, 0x41, 0x21, 0xcb, 0x0c, 0x3a, 0x66, 0x6b, 0xdd, 0x84, 0x3a, 0x5e, 0xa9, 0x64, 0xe8,
	0x41, 0xa9, 0x2f, 0x84, 0x5a, 0x40, 0x94, 0x54, 0x2c, 0x9f, 0x9c, 0x6c, 0x46, 0x59, 0x23, 0x1f,
	0xfa, 0xe4, 0x06, 0x54, 0x48, 0xf4, 0x12, 0xda, 0x3c, 0xdf, 0x3d, 0xe9, 0xe7, 0x83, 0xdc, 0xd2,
	0x0d, 0x1d, 0x14, 0xcd, 0x9e, 0xfb, 0x75, 0xcf, 0xfd, 0x9f, 0x9f, 0xff, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x9d, 0x35, 0x6b, 0x69, 0xcf, 0x05, 0x00, 0x00,
}
