// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Opener struct {
	OpenerId             string   `protobuf:"bytes,1,opt,name=openerId,proto3" json:"openerId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Opener) Reset()         { *m = Opener{} }
func (m *Opener) String() string { return proto.CompactTextString(m) }
func (*Opener) ProtoMessage()    {}
func (*Opener) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{0}
}
func (m *Opener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Opener.Unmarshal(m, b)
}
func (m *Opener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Opener.Marshal(b, m, deterministic)
}
func (dst *Opener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Opener.Merge(dst, src)
}
func (m *Opener) XXX_Size() int {
	return xxx_messageInfo_Opener.Size(m)
}
func (m *Opener) XXX_DiscardUnknown() {
	xxx_messageInfo_Opener.DiscardUnknown(m)
}

var xxx_messageInfo_Opener proto.InternalMessageInfo

func (m *Opener) GetOpenerId() string {
	if m != nil {
		return m.OpenerId
	}
	return ""
}

func (m *Opener) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ListOpenersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOpenersRequest) Reset()         { *m = ListOpenersRequest{} }
func (m *ListOpenersRequest) String() string { return proto.CompactTextString(m) }
func (*ListOpenersRequest) ProtoMessage()    {}
func (*ListOpenersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{2}
}
func (m *ListOpenersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOpenersRequest.Unmarshal(m, b)
}
func (m *ListOpenersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOpenersRequest.Marshal(b, m, deterministic)
}
func (dst *ListOpenersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOpenersRequest.Merge(dst, src)
}
func (m *ListOpenersRequest) XXX_Size() int {
	return xxx_messageInfo_ListOpenersRequest.Size(m)
}
func (m *ListOpenersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOpenersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOpenersRequest proto.InternalMessageInfo

type ListOpenersResponse struct {
	Openers              []*Opener `protobuf:"bytes,1,rep,name=openers,proto3" json:"openers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListOpenersResponse) Reset()         { *m = ListOpenersResponse{} }
func (m *ListOpenersResponse) String() string { return proto.CompactTextString(m) }
func (*ListOpenersResponse) ProtoMessage()    {}
func (*ListOpenersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{3}
}
func (m *ListOpenersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOpenersResponse.Unmarshal(m, b)
}
func (m *ListOpenersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOpenersResponse.Marshal(b, m, deterministic)
}
func (dst *ListOpenersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOpenersResponse.Merge(dst, src)
}
func (m *ListOpenersResponse) XXX_Size() int {
	return xxx_messageInfo_ListOpenersResponse.Size(m)
}
func (m *ListOpenersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOpenersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOpenersResponse proto.InternalMessageInfo

func (m *ListOpenersResponse) GetOpeners() []*Opener {
	if m != nil {
		return m.Openers
	}
	return nil
}

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{4}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{5}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type AddPortForUserAndOpenerRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OpenerId             string   `protobuf:"bytes,2,opt,name=openerId,proto3" json:"openerId,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocols            string   `protobuf:"bytes,4,opt,name=protocols,proto3" json:"protocols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPortForUserAndOpenerRequest) Reset()         { *m = AddPortForUserAndOpenerRequest{} }
func (m *AddPortForUserAndOpenerRequest) String() string { return proto.CompactTextString(m) }
func (*AddPortForUserAndOpenerRequest) ProtoMessage()    {}
func (*AddPortForUserAndOpenerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{6}
}
func (m *AddPortForUserAndOpenerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPortForUserAndOpenerRequest.Unmarshal(m, b)
}
func (m *AddPortForUserAndOpenerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPortForUserAndOpenerRequest.Marshal(b, m, deterministic)
}
func (dst *AddPortForUserAndOpenerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPortForUserAndOpenerRequest.Merge(dst, src)
}
func (m *AddPortForUserAndOpenerRequest) XXX_Size() int {
	return xxx_messageInfo_AddPortForUserAndOpenerRequest.Size(m)
}
func (m *AddPortForUserAndOpenerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPortForUserAndOpenerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPortForUserAndOpenerRequest proto.InternalMessageInfo

func (m *AddPortForUserAndOpenerRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddPortForUserAndOpenerRequest) GetOpenerId() string {
	if m != nil {
		return m.OpenerId
	}
	return ""
}

func (m *AddPortForUserAndOpenerRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *AddPortForUserAndOpenerRequest) GetProtocols() string {
	if m != nil {
		return m.Protocols
	}
	return ""
}

type AddPortForUserAndOpenerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPortForUserAndOpenerResponse) Reset()         { *m = AddPortForUserAndOpenerResponse{} }
func (m *AddPortForUserAndOpenerResponse) String() string { return proto.CompactTextString(m) }
func (*AddPortForUserAndOpenerResponse) ProtoMessage()    {}
func (*AddPortForUserAndOpenerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{7}
}
func (m *AddPortForUserAndOpenerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPortForUserAndOpenerResponse.Unmarshal(m, b)
}
func (m *AddPortForUserAndOpenerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPortForUserAndOpenerResponse.Marshal(b, m, deterministic)
}
func (dst *AddPortForUserAndOpenerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPortForUserAndOpenerResponse.Merge(dst, src)
}
func (m *AddPortForUserAndOpenerResponse) XXX_Size() int {
	return xxx_messageInfo_AddPortForUserAndOpenerResponse.Size(m)
}
func (m *AddPortForUserAndOpenerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPortForUserAndOpenerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPortForUserAndOpenerResponse proto.InternalMessageInfo

type DelPortForUserAndOpenerRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OpenerId             string   `protobuf:"bytes,2,opt,name=openerId,proto3" json:"openerId,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelPortForUserAndOpenerRequest) Reset()         { *m = DelPortForUserAndOpenerRequest{} }
func (m *DelPortForUserAndOpenerRequest) String() string { return proto.CompactTextString(m) }
func (*DelPortForUserAndOpenerRequest) ProtoMessage()    {}
func (*DelPortForUserAndOpenerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{8}
}
func (m *DelPortForUserAndOpenerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelPortForUserAndOpenerRequest.Unmarshal(m, b)
}
func (m *DelPortForUserAndOpenerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelPortForUserAndOpenerRequest.Marshal(b, m, deterministic)
}
func (dst *DelPortForUserAndOpenerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelPortForUserAndOpenerRequest.Merge(dst, src)
}
func (m *DelPortForUserAndOpenerRequest) XXX_Size() int {
	return xxx_messageInfo_DelPortForUserAndOpenerRequest.Size(m)
}
func (m *DelPortForUserAndOpenerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelPortForUserAndOpenerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelPortForUserAndOpenerRequest proto.InternalMessageInfo

func (m *DelPortForUserAndOpenerRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DelPortForUserAndOpenerRequest) GetOpenerId() string {
	if m != nil {
		return m.OpenerId
	}
	return ""
}

func (m *DelPortForUserAndOpenerRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type DelPortForUserAndOpenerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelPortForUserAndOpenerResponse) Reset()         { *m = DelPortForUserAndOpenerResponse{} }
func (m *DelPortForUserAndOpenerResponse) String() string { return proto.CompactTextString(m) }
func (*DelPortForUserAndOpenerResponse) ProtoMessage()    {}
func (*DelPortForUserAndOpenerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{9}
}
func (m *DelPortForUserAndOpenerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelPortForUserAndOpenerResponse.Unmarshal(m, b)
}
func (m *DelPortForUserAndOpenerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelPortForUserAndOpenerResponse.Marshal(b, m, deterministic)
}
func (dst *DelPortForUserAndOpenerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelPortForUserAndOpenerResponse.Merge(dst, src)
}
func (m *DelPortForUserAndOpenerResponse) XXX_Size() int {
	return xxx_messageInfo_DelPortForUserAndOpenerResponse.Size(m)
}
func (m *DelPortForUserAndOpenerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelPortForUserAndOpenerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelPortForUserAndOpenerResponse proto.InternalMessageInfo

type OpenerAndPort struct {
	OpenerId             string   `protobuf:"bytes,1,opt,name=openerId,proto3" json:"openerId,omitempty"`
	OpenerName           string   `protobuf:"bytes,2,opt,name=openerName,proto3" json:"openerName,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocols            string   `protobuf:"bytes,4,opt,name=protocols,proto3" json:"protocols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenerAndPort) Reset()         { *m = OpenerAndPort{} }
func (m *OpenerAndPort) String() string { return proto.CompactTextString(m) }
func (*OpenerAndPort) ProtoMessage()    {}
func (*OpenerAndPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{10}
}
func (m *OpenerAndPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenerAndPort.Unmarshal(m, b)
}
func (m *OpenerAndPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenerAndPort.Marshal(b, m, deterministic)
}
func (dst *OpenerAndPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenerAndPort.Merge(dst, src)
}
func (m *OpenerAndPort) XXX_Size() int {
	return xxx_messageInfo_OpenerAndPort.Size(m)
}
func (m *OpenerAndPort) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenerAndPort.DiscardUnknown(m)
}

var xxx_messageInfo_OpenerAndPort proto.InternalMessageInfo

func (m *OpenerAndPort) GetOpenerId() string {
	if m != nil {
		return m.OpenerId
	}
	return ""
}

func (m *OpenerAndPort) GetOpenerName() string {
	if m != nil {
		return m.OpenerName
	}
	return ""
}

func (m *OpenerAndPort) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *OpenerAndPort) GetProtocols() string {
	if m != nil {
		return m.Protocols
	}
	return ""
}

type ListPortsForUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPortsForUserRequest) Reset()         { *m = ListPortsForUserRequest{} }
func (m *ListPortsForUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListPortsForUserRequest) ProtoMessage()    {}
func (*ListPortsForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{11}
}
func (m *ListPortsForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPortsForUserRequest.Unmarshal(m, b)
}
func (m *ListPortsForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPortsForUserRequest.Marshal(b, m, deterministic)
}
func (dst *ListPortsForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPortsForUserRequest.Merge(dst, src)
}
func (m *ListPortsForUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListPortsForUserRequest.Size(m)
}
func (m *ListPortsForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPortsForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPortsForUserRequest proto.InternalMessageInfo

func (m *ListPortsForUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListPortsForUserResponse struct {
	Result               []*OpenerAndPort `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListPortsForUserResponse) Reset()         { *m = ListPortsForUserResponse{} }
func (m *ListPortsForUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListPortsForUserResponse) ProtoMessage()    {}
func (*ListPortsForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{12}
}
func (m *ListPortsForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPortsForUserResponse.Unmarshal(m, b)
}
func (m *ListPortsForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPortsForUserResponse.Marshal(b, m, deterministic)
}
func (dst *ListPortsForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPortsForUserResponse.Merge(dst, src)
}
func (m *ListPortsForUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListPortsForUserResponse.Size(m)
}
func (m *ListPortsForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPortsForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPortsForUserResponse proto.InternalMessageInfo

func (m *ListPortsForUserResponse) GetResult() []*OpenerAndPort {
	if m != nil {
		return m.Result
	}
	return nil
}

type UserAndPort struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Port                 string   `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Protocols            string   `protobuf:"bytes,5,opt,name=protocols,proto3" json:"protocols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAndPort) Reset()         { *m = UserAndPort{} }
func (m *UserAndPort) String() string { return proto.CompactTextString(m) }
func (*UserAndPort) ProtoMessage()    {}
func (*UserAndPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{13}
}
func (m *UserAndPort) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAndPort.Unmarshal(m, b)
}
func (m *UserAndPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAndPort.Marshal(b, m, deterministic)
}
func (dst *UserAndPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAndPort.Merge(dst, src)
}
func (m *UserAndPort) XXX_Size() int {
	return xxx_messageInfo_UserAndPort.Size(m)
}
func (m *UserAndPort) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAndPort.DiscardUnknown(m)
}

var xxx_messageInfo_UserAndPort proto.InternalMessageInfo

func (m *UserAndPort) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserAndPort) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserAndPort) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserAndPort) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *UserAndPort) GetProtocols() string {
	if m != nil {
		return m.Protocols
	}
	return ""
}

type ListPortsForOpenerRequest struct {
	OpenerId             string   `protobuf:"bytes,1,opt,name=openerId,proto3" json:"openerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPortsForOpenerRequest) Reset()         { *m = ListPortsForOpenerRequest{} }
func (m *ListPortsForOpenerRequest) String() string { return proto.CompactTextString(m) }
func (*ListPortsForOpenerRequest) ProtoMessage()    {}
func (*ListPortsForOpenerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{14}
}
func (m *ListPortsForOpenerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPortsForOpenerRequest.Unmarshal(m, b)
}
func (m *ListPortsForOpenerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPortsForOpenerRequest.Marshal(b, m, deterministic)
}
func (dst *ListPortsForOpenerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPortsForOpenerRequest.Merge(dst, src)
}
func (m *ListPortsForOpenerRequest) XXX_Size() int {
	return xxx_messageInfo_ListPortsForOpenerRequest.Size(m)
}
func (m *ListPortsForOpenerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPortsForOpenerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPortsForOpenerRequest proto.InternalMessageInfo

func (m *ListPortsForOpenerRequest) GetOpenerId() string {
	if m != nil {
		return m.OpenerId
	}
	return ""
}

type ListPortsForOpenerResponse struct {
	Result               []*UserAndPort `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPortsForOpenerResponse) Reset()         { *m = ListPortsForOpenerResponse{} }
func (m *ListPortsForOpenerResponse) String() string { return proto.CompactTextString(m) }
func (*ListPortsForOpenerResponse) ProtoMessage()    {}
func (*ListPortsForOpenerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{15}
}
func (m *ListPortsForOpenerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPortsForOpenerResponse.Unmarshal(m, b)
}
func (m *ListPortsForOpenerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPortsForOpenerResponse.Marshal(b, m, deterministic)
}
func (dst *ListPortsForOpenerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPortsForOpenerResponse.Merge(dst, src)
}
func (m *ListPortsForOpenerResponse) XXX_Size() int {
	return xxx_messageInfo_ListPortsForOpenerResponse.Size(m)
}
func (m *ListPortsForOpenerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPortsForOpenerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPortsForOpenerResponse proto.InternalMessageInfo

func (m *ListPortsForOpenerResponse) GetResult() []*UserAndPort {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListActiveIpsForUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Local                string   `protobuf:"bytes,2,opt,name=local,proto3" json:"local,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActiveIpsForUserRequest) Reset()         { *m = ListActiveIpsForUserRequest{} }
func (m *ListActiveIpsForUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListActiveIpsForUserRequest) ProtoMessage()    {}
func (*ListActiveIpsForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{16}
}
func (m *ListActiveIpsForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActiveIpsForUserRequest.Unmarshal(m, b)
}
func (m *ListActiveIpsForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActiveIpsForUserRequest.Marshal(b, m, deterministic)
}
func (dst *ListActiveIpsForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActiveIpsForUserRequest.Merge(dst, src)
}
func (m *ListActiveIpsForUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListActiveIpsForUserRequest.Size(m)
}
func (m *ListActiveIpsForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActiveIpsForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListActiveIpsForUserRequest proto.InternalMessageInfo

func (m *ListActiveIpsForUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListActiveIpsForUserRequest) GetLocal() string {
	if m != nil {
		return m.Local
	}
	return ""
}

type ListActiveIpsForUserResponse struct {
	Result               []string `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListActiveIpsForUserResponse) Reset()         { *m = ListActiveIpsForUserResponse{} }
func (m *ListActiveIpsForUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListActiveIpsForUserResponse) ProtoMessage()    {}
func (*ListActiveIpsForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{17}
}
func (m *ListActiveIpsForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListActiveIpsForUserResponse.Unmarshal(m, b)
}
func (m *ListActiveIpsForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListActiveIpsForUserResponse.Marshal(b, m, deterministic)
}
func (dst *ListActiveIpsForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListActiveIpsForUserResponse.Merge(dst, src)
}
func (m *ListActiveIpsForUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListActiveIpsForUserResponse.Size(m)
}
func (m *ListActiveIpsForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListActiveIpsForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListActiveIpsForUserResponse proto.InternalMessageInfo

func (m *ListActiveIpsForUserResponse) GetResult() []string {
	if m != nil {
		return m.Result
	}
	return nil
}

type AddServiceToUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddServiceToUserRequest) Reset()         { *m = AddServiceToUserRequest{} }
func (m *AddServiceToUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddServiceToUserRequest) ProtoMessage()    {}
func (*AddServiceToUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{18}
}
func (m *AddServiceToUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddServiceToUserRequest.Unmarshal(m, b)
}
func (m *AddServiceToUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddServiceToUserRequest.Marshal(b, m, deterministic)
}
func (dst *AddServiceToUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddServiceToUserRequest.Merge(dst, src)
}
func (m *AddServiceToUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddServiceToUserRequest.Size(m)
}
func (m *AddServiceToUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddServiceToUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddServiceToUserRequest proto.InternalMessageInfo

func (m *AddServiceToUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddServiceToUserRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type AddServiceToUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddServiceToUserResponse) Reset()         { *m = AddServiceToUserResponse{} }
func (m *AddServiceToUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddServiceToUserResponse) ProtoMessage()    {}
func (*AddServiceToUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{19}
}
func (m *AddServiceToUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddServiceToUserResponse.Unmarshal(m, b)
}
func (m *AddServiceToUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddServiceToUserResponse.Marshal(b, m, deterministic)
}
func (dst *AddServiceToUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddServiceToUserResponse.Merge(dst, src)
}
func (m *AddServiceToUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddServiceToUserResponse.Size(m)
}
func (m *AddServiceToUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddServiceToUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddServiceToUserResponse proto.InternalMessageInfo

type ListServicesForUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesForUserRequest) Reset()         { *m = ListServicesForUserRequest{} }
func (m *ListServicesForUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListServicesForUserRequest) ProtoMessage()    {}
func (*ListServicesForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{20}
}
func (m *ListServicesForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesForUserRequest.Unmarshal(m, b)
}
func (m *ListServicesForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesForUserRequest.Marshal(b, m, deterministic)
}
func (dst *ListServicesForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesForUserRequest.Merge(dst, src)
}
func (m *ListServicesForUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListServicesForUserRequest.Size(m)
}
func (m *ListServicesForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesForUserRequest proto.InternalMessageInfo

func (m *ListServicesForUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListServicesForUserResponse struct {
	Services             []string `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServicesForUserResponse) Reset()         { *m = ListServicesForUserResponse{} }
func (m *ListServicesForUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListServicesForUserResponse) ProtoMessage()    {}
func (*ListServicesForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{21}
}
func (m *ListServicesForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServicesForUserResponse.Unmarshal(m, b)
}
func (m *ListServicesForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServicesForUserResponse.Marshal(b, m, deterministic)
}
func (dst *ListServicesForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServicesForUserResponse.Merge(dst, src)
}
func (m *ListServicesForUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListServicesForUserResponse.Size(m)
}
func (m *ListServicesForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServicesForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServicesForUserResponse proto.InternalMessageInfo

func (m *ListServicesForUserResponse) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

type DelServiceToUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Service              string   `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelServiceToUserRequest) Reset()         { *m = DelServiceToUserRequest{} }
func (m *DelServiceToUserRequest) String() string { return proto.CompactTextString(m) }
func (*DelServiceToUserRequest) ProtoMessage()    {}
func (*DelServiceToUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{22}
}
func (m *DelServiceToUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelServiceToUserRequest.Unmarshal(m, b)
}
func (m *DelServiceToUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelServiceToUserRequest.Marshal(b, m, deterministic)
}
func (dst *DelServiceToUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelServiceToUserRequest.Merge(dst, src)
}
func (m *DelServiceToUserRequest) XXX_Size() int {
	return xxx_messageInfo_DelServiceToUserRequest.Size(m)
}
func (m *DelServiceToUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelServiceToUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelServiceToUserRequest proto.InternalMessageInfo

func (m *DelServiceToUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DelServiceToUserRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type DelServiceToUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelServiceToUserResponse) Reset()         { *m = DelServiceToUserResponse{} }
func (m *DelServiceToUserResponse) String() string { return proto.CompactTextString(m) }
func (*DelServiceToUserResponse) ProtoMessage()    {}
func (*DelServiceToUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{23}
}
func (m *DelServiceToUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelServiceToUserResponse.Unmarshal(m, b)
}
func (m *DelServiceToUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelServiceToUserResponse.Marshal(b, m, deterministic)
}
func (dst *DelServiceToUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelServiceToUserResponse.Merge(dst, src)
}
func (m *DelServiceToUserResponse) XXX_Size() int {
	return xxx_messageInfo_DelServiceToUserResponse.Size(m)
}
func (m *DelServiceToUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelServiceToUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelServiceToUserResponse proto.InternalMessageInfo

type PutUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUserRequest) Reset()         { *m = PutUserRequest{} }
func (m *PutUserRequest) String() string { return proto.CompactTextString(m) }
func (*PutUserRequest) ProtoMessage()    {}
func (*PutUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{24}
}
func (m *PutUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUserRequest.Unmarshal(m, b)
}
func (m *PutUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUserRequest.Marshal(b, m, deterministic)
}
func (dst *PutUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUserRequest.Merge(dst, src)
}
func (m *PutUserRequest) XXX_Size() int {
	return xxx_messageInfo_PutUserRequest.Size(m)
}
func (m *PutUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutUserRequest proto.InternalMessageInfo

func (m *PutUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type PutUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutUserResponse) Reset()         { *m = PutUserResponse{} }
func (m *PutUserResponse) String() string { return proto.CompactTextString(m) }
func (*PutUserResponse) ProtoMessage()    {}
func (*PutUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{25}
}
func (m *PutUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutUserResponse.Unmarshal(m, b)
}
func (m *PutUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutUserResponse.Marshal(b, m, deterministic)
}
func (dst *PutUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutUserResponse.Merge(dst, src)
}
func (m *PutUserResponse) XXX_Size() int {
	return xxx_messageInfo_PutUserResponse.Size(m)
}
func (m *PutUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutUserResponse proto.InternalMessageInfo

type DelUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserRequest) Reset()         { *m = DelUserRequest{} }
func (m *DelUserRequest) String() string { return proto.CompactTextString(m) }
func (*DelUserRequest) ProtoMessage()    {}
func (*DelUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{26}
}
func (m *DelUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserRequest.Unmarshal(m, b)
}
func (m *DelUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserRequest.Marshal(b, m, deterministic)
}
func (dst *DelUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserRequest.Merge(dst, src)
}
func (m *DelUserRequest) XXX_Size() int {
	return xxx_messageInfo_DelUserRequest.Size(m)
}
func (m *DelUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserRequest proto.InternalMessageInfo

func (m *DelUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DelUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUserResponse) Reset()         { *m = DelUserResponse{} }
func (m *DelUserResponse) String() string { return proto.CompactTextString(m) }
func (*DelUserResponse) ProtoMessage()    {}
func (*DelUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{27}
}
func (m *DelUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUserResponse.Unmarshal(m, b)
}
func (m *DelUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUserResponse.Marshal(b, m, deterministic)
}
func (dst *DelUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUserResponse.Merge(dst, src)
}
func (m *DelUserResponse) XXX_Size() int {
	return xxx_messageInfo_DelUserResponse.Size(m)
}
func (m *DelUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelUserResponse proto.InternalMessageInfo

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{28}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_71b5787e127c94e8, []int{29}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(dst, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Opener)(nil), "api.Opener")
	proto.RegisterType((*User)(nil), "api.User")
	proto.RegisterType((*ListOpenersRequest)(nil), "api.ListOpenersRequest")
	proto.RegisterType((*ListOpenersResponse)(nil), "api.ListOpenersResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "api.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "api.ListUsersResponse")
	proto.RegisterType((*AddPortForUserAndOpenerRequest)(nil), "api.AddPortForUserAndOpenerRequest")
	proto.RegisterType((*AddPortForUserAndOpenerResponse)(nil), "api.AddPortForUserAndOpenerResponse")
	proto.RegisterType((*DelPortForUserAndOpenerRequest)(nil), "api.DelPortForUserAndOpenerRequest")
	proto.RegisterType((*DelPortForUserAndOpenerResponse)(nil), "api.DelPortForUserAndOpenerResponse")
	proto.RegisterType((*OpenerAndPort)(nil), "api.OpenerAndPort")
	proto.RegisterType((*ListPortsForUserRequest)(nil), "api.ListPortsForUserRequest")
	proto.RegisterType((*ListPortsForUserResponse)(nil), "api.ListPortsForUserResponse")
	proto.RegisterType((*UserAndPort)(nil), "api.UserAndPort")
	proto.RegisterType((*ListPortsForOpenerRequest)(nil), "api.ListPortsForOpenerRequest")
	proto.RegisterType((*ListPortsForOpenerResponse)(nil), "api.ListPortsForOpenerResponse")
	proto.RegisterType((*ListActiveIpsForUserRequest)(nil), "api.ListActiveIpsForUserRequest")
	proto.RegisterType((*ListActiveIpsForUserResponse)(nil), "api.ListActiveIpsForUserResponse")
	proto.RegisterType((*AddServiceToUserRequest)(nil), "api.AddServiceToUserRequest")
	proto.RegisterType((*AddServiceToUserResponse)(nil), "api.AddServiceToUserResponse")
	proto.RegisterType((*ListServicesForUserRequest)(nil), "api.ListServicesForUserRequest")
	proto.RegisterType((*ListServicesForUserResponse)(nil), "api.ListServicesForUserResponse")
	proto.RegisterType((*DelServiceToUserRequest)(nil), "api.DelServiceToUserRequest")
	proto.RegisterType((*DelServiceToUserResponse)(nil), "api.DelServiceToUserResponse")
	proto.RegisterType((*PutUserRequest)(nil), "api.PutUserRequest")
	proto.RegisterType((*PutUserResponse)(nil), "api.PutUserResponse")
	proto.RegisterType((*DelUserRequest)(nil), "api.DelUserRequest")
	proto.RegisterType((*DelUserResponse)(nil), "api.DelUserResponse")
	proto.RegisterType((*GetUserRequest)(nil), "api.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "api.GetUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IdentityProviderAdminClient is the client API for IdentityProviderAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IdentityProviderAdminClient interface {
	ListOpeners(ctx context.Context, in *ListOpenersRequest, opts ...grpc.CallOption) (*ListOpenersResponse, error)
	PutUser(ctx context.Context, in *PutUserRequest, opts ...grpc.CallOption) (*PutUserResponse, error)
	DelUser(ctx context.Context, in *DelUserRequest, opts ...grpc.CallOption) (*DelUserResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	AddPortForUserAndOpener(ctx context.Context, in *AddPortForUserAndOpenerRequest, opts ...grpc.CallOption) (*AddPortForUserAndOpenerResponse, error)
	DelPortForUserAndOpener(ctx context.Context, in *DelPortForUserAndOpenerRequest, opts ...grpc.CallOption) (*DelPortForUserAndOpenerResponse, error)
	ListPortsForUser(ctx context.Context, in *ListPortsForUserRequest, opts ...grpc.CallOption) (*ListPortsForUserResponse, error)
	ListPortsForOpener(ctx context.Context, in *ListPortsForOpenerRequest, opts ...grpc.CallOption) (*ListPortsForOpenerResponse, error)
	ListActiveIpsForUser(ctx context.Context, in *ListActiveIpsForUserRequest, opts ...grpc.CallOption) (*ListActiveIpsForUserResponse, error)
	AddServiceToUser(ctx context.Context, in *AddServiceToUserRequest, opts ...grpc.CallOption) (*AddServiceToUserResponse, error)
	ListServicesForUser(ctx context.Context, in *ListServicesForUserRequest, opts ...grpc.CallOption) (*ListServicesForUserResponse, error)
	DelServiceToUser(ctx context.Context, in *DelServiceToUserRequest, opts ...grpc.CallOption) (*DelServiceToUserResponse, error)
}

type identityProviderAdminClient struct {
	cc *grpc.ClientConn
}

func NewIdentityProviderAdminClient(cc *grpc.ClientConn) IdentityProviderAdminClient {
	return &identityProviderAdminClient{cc}
}

func (c *identityProviderAdminClient) ListOpeners(ctx context.Context, in *ListOpenersRequest, opts ...grpc.CallOption) (*ListOpenersResponse, error) {
	out := new(ListOpenersResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/listOpeners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) PutUser(ctx context.Context, in *PutUserRequest, opts ...grpc.CallOption) (*PutUserResponse, error) {
	out := new(PutUserResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/putUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) DelUser(ctx context.Context, in *DelUserRequest, opts ...grpc.CallOption) (*DelUserResponse, error) {
	out := new(DelUserResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/delUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/getUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/listUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) AddPortForUserAndOpener(ctx context.Context, in *AddPortForUserAndOpenerRequest, opts ...grpc.CallOption) (*AddPortForUserAndOpenerResponse, error) {
	out := new(AddPortForUserAndOpenerResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/addPortForUserAndOpener", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) DelPortForUserAndOpener(ctx context.Context, in *DelPortForUserAndOpenerRequest, opts ...grpc.CallOption) (*DelPortForUserAndOpenerResponse, error) {
	out := new(DelPortForUserAndOpenerResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/delPortForUserAndOpener", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) ListPortsForUser(ctx context.Context, in *ListPortsForUserRequest, opts ...grpc.CallOption) (*ListPortsForUserResponse, error) {
	out := new(ListPortsForUserResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/listPortsForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) ListPortsForOpener(ctx context.Context, in *ListPortsForOpenerRequest, opts ...grpc.CallOption) (*ListPortsForOpenerResponse, error) {
	out := new(ListPortsForOpenerResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/listPortsForOpener", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) ListActiveIpsForUser(ctx context.Context, in *ListActiveIpsForUserRequest, opts ...grpc.CallOption) (*ListActiveIpsForUserResponse, error) {
	out := new(ListActiveIpsForUserResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/listActiveIpsForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) AddServiceToUser(ctx context.Context, in *AddServiceToUserRequest, opts ...grpc.CallOption) (*AddServiceToUserResponse, error) {
	out := new(AddServiceToUserResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/addServiceToUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) ListServicesForUser(ctx context.Context, in *ListServicesForUserRequest, opts ...grpc.CallOption) (*ListServicesForUserResponse, error) {
	out := new(ListServicesForUserResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/listServicesForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityProviderAdminClient) DelServiceToUser(ctx context.Context, in *DelServiceToUserRequest, opts ...grpc.CallOption) (*DelServiceToUserResponse, error) {
	out := new(DelServiceToUserResponse)
	err := c.cc.Invoke(ctx, "/api.IdentityProviderAdmin/delServiceToUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityProviderAdminServer is the server API for IdentityProviderAdmin service.
type IdentityProviderAdminServer interface {
	ListOpeners(context.Context, *ListOpenersRequest) (*ListOpenersResponse, error)
	PutUser(context.Context, *PutUserRequest) (*PutUserResponse, error)
	DelUser(context.Context, *DelUserRequest) (*DelUserResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	AddPortForUserAndOpener(context.Context, *AddPortForUserAndOpenerRequest) (*AddPortForUserAndOpenerResponse, error)
	DelPortForUserAndOpener(context.Context, *DelPortForUserAndOpenerRequest) (*DelPortForUserAndOpenerResponse, error)
	ListPortsForUser(context.Context, *ListPortsForUserRequest) (*ListPortsForUserResponse, error)
	ListPortsForOpener(context.Context, *ListPortsForOpenerRequest) (*ListPortsForOpenerResponse, error)
	ListActiveIpsForUser(context.Context, *ListActiveIpsForUserRequest) (*ListActiveIpsForUserResponse, error)
	AddServiceToUser(context.Context, *AddServiceToUserRequest) (*AddServiceToUserResponse, error)
	ListServicesForUser(context.Context, *ListServicesForUserRequest) (*ListServicesForUserResponse, error)
	DelServiceToUser(context.Context, *DelServiceToUserRequest) (*DelServiceToUserResponse, error)
}

func RegisterIdentityProviderAdminServer(s *grpc.Server, srv IdentityProviderAdminServer) {
	s.RegisterService(&_IdentityProviderAdmin_serviceDesc, srv)
}

func _IdentityProviderAdmin_ListOpeners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOpenersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).ListOpeners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/ListOpeners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).ListOpeners(ctx, req.(*ListOpenersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_PutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).PutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/PutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).PutUser(ctx, req.(*PutUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_DelUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).DelUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/DelUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).DelUser(ctx, req.(*DelUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_AddPortForUserAndOpener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPortForUserAndOpenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).AddPortForUserAndOpener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/AddPortForUserAndOpener",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).AddPortForUserAndOpener(ctx, req.(*AddPortForUserAndOpenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_DelPortForUserAndOpener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelPortForUserAndOpenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).DelPortForUserAndOpener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/DelPortForUserAndOpener",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).DelPortForUserAndOpener(ctx, req.(*DelPortForUserAndOpenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_ListPortsForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortsForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).ListPortsForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/ListPortsForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).ListPortsForUser(ctx, req.(*ListPortsForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_ListPortsForOpener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortsForOpenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).ListPortsForOpener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/ListPortsForOpener",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).ListPortsForOpener(ctx, req.(*ListPortsForOpenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_ListActiveIpsForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveIpsForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).ListActiveIpsForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/ListActiveIpsForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).ListActiveIpsForUser(ctx, req.(*ListActiveIpsForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_AddServiceToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServiceToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).AddServiceToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/AddServiceToUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).AddServiceToUser(ctx, req.(*AddServiceToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_ListServicesForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).ListServicesForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/ListServicesForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).ListServicesForUser(ctx, req.(*ListServicesForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityProviderAdmin_DelServiceToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelServiceToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityProviderAdminServer).DelServiceToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.IdentityProviderAdmin/DelServiceToUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityProviderAdminServer).DelServiceToUser(ctx, req.(*DelServiceToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IdentityProviderAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.IdentityProviderAdmin",
	HandlerType: (*IdentityProviderAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listOpeners",
			Handler:    _IdentityProviderAdmin_ListOpeners_Handler,
		},
		{
			MethodName: "putUser",
			Handler:    _IdentityProviderAdmin_PutUser_Handler,
		},
		{
			MethodName: "delUser",
			Handler:    _IdentityProviderAdmin_DelUser_Handler,
		},
		{
			MethodName: "getUser",
			Handler:    _IdentityProviderAdmin_GetUser_Handler,
		},
		{
			MethodName: "listUsers",
			Handler:    _IdentityProviderAdmin_ListUsers_Handler,
		},
		{
			MethodName: "addPortForUserAndOpener",
			Handler:    _IdentityProviderAdmin_AddPortForUserAndOpener_Handler,
		},
		{
			MethodName: "delPortForUserAndOpener",
			Handler:    _IdentityProviderAdmin_DelPortForUserAndOpener_Handler,
		},
		{
			MethodName: "listPortsForUser",
			Handler:    _IdentityProviderAdmin_ListPortsForUser_Handler,
		},
		{
			MethodName: "listPortsForOpener",
			Handler:    _IdentityProviderAdmin_ListPortsForOpener_Handler,
		},
		{
			MethodName: "listActiveIpsForUser",
			Handler:    _IdentityProviderAdmin_ListActiveIpsForUser_Handler,
		},
		{
			MethodName: "addServiceToUser",
			Handler:    _IdentityProviderAdmin_AddServiceToUser_Handler,
		},
		{
			MethodName: "listServicesForUser",
			Handler:    _IdentityProviderAdmin_ListServicesForUser_Handler,
		},
		{
			MethodName: "delServiceToUser",
			Handler:    _IdentityProviderAdmin_DelServiceToUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_71b5787e127c94e8) }

var fileDescriptor_api_71b5787e127c94e8 = []byte{
	// 802 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdf, 0x4b, 0x1b, 0x4b,
	0x14, 0x26, 0x1a, 0xa3, 0x39, 0xe1, 0xfa, 0x63, 0x8c, 0x66, 0xef, 0xde, 0x18, 0xe3, 0xde, 0x7b,
	0x21, 0xf4, 0x41, 0x5b, 0x2b, 0xfd, 0x45, 0x1f, 0x1a, 0x10, 0x8b, 0xb4, 0x54, 0x49, 0x2b, 0x14,
	0x0a, 0x85, 0x6d, 0x76, 0xd0, 0x85, 0x71, 0x67, 0xbb, 0x33, 0x11, 0x7c, 0xe8, 0x53, 0x4b, 0xff,
	0xee, 0x32, 0x33, 0x27, 0xfb, 0x33, 0xbb, 0x86, 0x22, 0x7d, 0x9b, 0x39, 0x73, 0xbe, 0x6f, 0xbe,
	0xf3, 0xed, 0xec, 0x39, 0xd0, 0x74, 0x43, 0x7f, 0x3f, 0x8c, 0xb8, 0xe4, 0x64, 0xd1, 0x0d, 0x7d,
	0xbb, 0x7b, 0xc9, 0xf9, 0x25, 0xa3, 0x07, 0x6e, 0xe8, 0x1f, 0xb8, 0x41, 0xc0, 0xa5, 0x2b, 0x7d,
	0x1e, 0x08, 0x93, 0xe2, 0x3c, 0x83, 0xc6, 0x59, 0x48, 0x03, 0x1a, 0x11, 0x1b, 0x56, 0xb8, 0x5e,
	0x9d, 0x7a, 0x56, 0xad, 0x5f, 0x1b, 0x34, 0x47, 0xf1, 0x9e, 0x10, 0xa8, 0x07, 0xee, 0x35, 0xb5,
	0x16, 0x74, 0x5c, 0xaf, 0x9d, 0xcf, 0x50, 0xbf, 0x10, 0x34, 0x22, 0xdb, 0xd0, 0x98, 0x88, 0x14,
	0x0a, 0x77, 0xa4, 0x0d, 0x4b, 0xf4, 0xda, 0xf5, 0x19, 0x82, 0xcc, 0x46, 0x45, 0xc3, 0x2b, 0x1e,
	0x50, 0x6b, 0xd1, 0x44, 0xf5, 0x46, 0xf1, 0xcb, 0xdb, 0x90, 0x5a, 0x75, 0xc3, 0xaf, 0xd6, 0x4e,
	0x1b, 0xc8, 0x5b, 0x5f, 0x48, 0xa3, 0x4e, 0x8c, 0xe8, 0xd7, 0x09, 0x15, 0xd2, 0x79, 0x09, 0x9b,
	0x99, 0xa8, 0x08, 0x79, 0x20, 0x28, 0xf9, 0x1f, 0x96, 0x8d, 0x58, 0x61, 0xd5, 0xfa, 0x8b, 0x83,
	0xd6, 0x61, 0x6b, 0x5f, 0xd9, 0x60, 0xd2, 0x46, 0xd3, 0x33, 0x87, 0xc0, 0xba, 0x42, 0x2b, 0xdd,
	0x31, 0xe3, 0x11, 0x6c, 0xa4, 0x62, 0xc8, 0xb7, 0x0b, 0x4b, 0xaa, 0x8c, 0x29, 0x5b, 0x53, 0xb3,
	0xa9, 0x94, 0x91, 0x89, 0x3b, 0x3f, 0x6b, 0xd0, 0x1b, 0x7a, 0xde, 0x39, 0x8f, 0xe4, 0x09, 0x8f,
	0xd4, 0xc9, 0x30, 0xf0, 0xf0, 0x3a, 0x43, 0x5c, 0x6a, 0x4c, 0xda, 0xe8, 0x85, 0xa2, 0xd1, 0x21,
	0x8f, 0x24, 0xba, 0xa3, 0xd7, 0xa4, 0x0b, 0x4d, 0xfd, 0xad, 0xc6, 0x9c, 0x09, 0x74, 0x28, 0x09,
	0x38, 0x7b, 0xb0, 0x5b, 0xaa, 0xc3, 0x14, 0xe3, 0x5c, 0x41, 0xef, 0x98, 0xb2, 0x3f, 0x20, 0x55,
	0x89, 0x29, 0xbd, 0x09, 0xc5, 0x7c, 0x83, 0xbf, 0x4c, 0x64, 0x18, 0x68, 0xd5, 0x95, 0xef, 0xae,
	0x07, 0x60, 0xd6, 0xef, 0x92, 0xd7, 0x97, 0x8a, 0xfc, 0x86, 0x5d, 0x8f, 0xa0, 0xa3, 0xbe, 0xb6,
	0xba, 0x59, 0xa0, 0xc6, 0x3b, 0x4c, 0x70, 0x4e, 0xc0, 0x2a, 0x42, 0xf0, 0x9d, 0x3c, 0x80, 0x46,
	0x44, 0xc5, 0x84, 0x49, 0x7c, 0x28, 0x24, 0xf5, 0xec, 0xb0, 0xc0, 0x11, 0x66, 0x38, 0xdf, 0x6b,
	0xd0, 0x42, 0x4f, 0x74, 0xe1, 0xf7, 0xf4, 0xe3, 0x68, 0x03, 0xea, 0x65, 0x06, 0x2c, 0xe5, 0x0d,
	0x78, 0x0a, 0x7f, 0xa7, 0xab, 0xc9, 0xbe, 0x83, 0x8a, 0x6f, 0xe1, 0x9c, 0x80, 0x3d, 0x0b, 0x88,
	0x46, 0x0c, 0x72, 0x46, 0xac, 0xc7, 0x7f, 0x4c, 0xde, 0x86, 0x37, 0xf0, 0x8f, 0xe2, 0x19, 0x8e,
	0xa5, 0x7f, 0x43, 0x4f, 0xc3, 0x39, 0xbf, 0x82, 0xaa, 0x9f, 0xf1, 0xb1, 0x1b, 0xbb, 0xa2, 0x37,
	0xce, 0x13, 0xe8, 0xce, 0x26, 0x43, 0x59, 0xdb, 0x19, 0x59, 0xcd, 0x94, 0x88, 0xce, 0xd0, 0xf3,
	0xde, 0xd3, 0xe8, 0xc6, 0x1f, 0xd3, 0x0f, 0x7c, 0x1e, 0x01, 0x16, 0x2c, 0x0b, 0x93, 0x8f, 0x12,
	0xa6, 0x5b, 0xc7, 0x06, 0xab, 0x48, 0x86, 0xcf, 0xfd, 0xc8, 0xb8, 0x86, 0x87, 0xf3, 0x3e, 0xb9,
	0xe7, 0xc6, 0xa3, 0x02, 0x0a, 0xab, 0xb2, 0x61, 0x05, 0xef, 0x16, 0xd6, 0x82, 0xae, 0x2b, 0xde,
	0xab, 0xca, 0x8e, 0x29, 0xbb, 0xbf, 0xca, 0x8a, 0x64, 0x58, 0xd9, 0x01, 0xac, 0x9e, 0x4f, 0x64,
	0x9a, 0x7f, 0x07, 0xea, 0x8a, 0x51, 0xb3, 0x67, 0x7a, 0xa6, 0x0e, 0x3b, 0x1b, 0xb0, 0x16, 0x03,
	0x90, 0x63, 0x00, 0xab, 0xc7, 0x94, 0xcd, 0xe3, 0xc8, 0x06, 0xac, 0xc5, 0x99, 0x09, 0xf8, 0x35,
	0x95, 0xf3, 0x80, 0x1f, 0xc2, 0x5a, 0x9c, 0x89, 0x16, 0x56, 0x6b, 0x3d, 0xfc, 0xb1, 0x02, 0x5b,
	0xa7, 0x1e, 0x0d, 0xa4, 0x2f, 0x6f, 0xcf, 0x23, 0x7e, 0xe3, 0x7b, 0x34, 0x1a, 0x7a, 0xd7, 0x7e,
	0x40, 0x5e, 0x41, 0x8b, 0x25, 0x03, 0x88, 0x74, 0x34, 0xb2, 0x38, 0xa8, 0x6c, 0xab, 0x78, 0x80,
	0x57, 0x1f, 0xc1, 0x72, 0x68, 0x7c, 0x20, 0x9b, 0x3a, 0x29, 0x6b, 0xa3, 0xdd, 0xce, 0x06, 0x13,
	0x94, 0x67, 0x0c, 0x40, 0x54, 0xd6, 0x38, 0x44, 0xe5, 0x3c, 0x52, 0xa8, 0x4b, 0x9a, 0xbe, 0x2b,
	0xeb, 0x18, 0xa2, 0xf2, 0xe6, 0xbc, 0x80, 0x26, 0x9b, 0x8e, 0x44, 0xb2, 0x15, 0x17, 0x92, 0x1e,
	0x9b, 0xf6, 0x76, 0x3e, 0x8c, 0x58, 0x0f, 0x3a, 0xee, 0xec, 0x79, 0x44, 0xfe, 0xd5, 0x90, 0xea,
	0xa9, 0x69, 0xff, 0x57, 0x9d, 0x94, 0xdc, 0xe2, 0xcd, 0x1e, 0x34, 0x78, 0x4b, 0xf5, 0xc0, 0xc3,
	0x5b, 0xee, 0x98, 0x55, 0xe4, 0x0c, 0xd6, 0x59, 0xae, 0xf3, 0x93, 0x6e, 0x5c, 0xf7, 0x8c, 0x19,
	0x62, 0xef, 0x94, 0x9c, 0x22, 0xe1, 0x05, 0x10, 0x56, 0xe8, 0xa1, 0xa4, 0x57, 0x00, 0x65, 0xc5,
	0xee, 0x96, 0x9e, 0x23, 0xed, 0x27, 0x68, 0xb3, 0x19, 0x5d, 0x90, 0xf4, 0x63, 0x60, 0x49, 0xb7,
	0xb5, 0xf7, 0x2a, 0x32, 0x12, 0x13, 0xdc, 0x5c, 0x77, 0x43, 0x13, 0x4a, 0x3a, 0x28, 0x9a, 0x50,
	0xd6, 0x12, 0xc9, 0x47, 0xd8, 0x64, 0xc5, 0xe6, 0x46, 0x92, 0x2a, 0x67, 0x37, 0x4b, 0xbb, 0x5f,
	0x9e, 0x90, 0x48, 0xf5, 0x72, 0xed, 0x0a, 0xa5, 0x96, 0xb4, 0x44, 0x94, 0x5a, 0xd6, 0xe3, 0xbe,
	0x34, 0xf4, 0xdc, 0x7c, 0xfc, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xfe, 0xc9, 0xe1, 0x54, 0x0b,
	0x00, 0x00,
}
