// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IdentityProvider struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdentityProvider) Reset()         { *m = IdentityProvider{} }
func (m *IdentityProvider) String() string { return proto.CompactTextString(m) }
func (*IdentityProvider) ProtoMessage()    {}
func (*IdentityProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{0}
}
func (m *IdentityProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityProvider.Unmarshal(m, b)
}
func (m *IdentityProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityProvider.Marshal(b, m, deterministic)
}
func (dst *IdentityProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityProvider.Merge(dst, src)
}
func (m *IdentityProvider) XXX_Size() int {
	return xxx_messageInfo_IdentityProvider.Size(m)
}
func (m *IdentityProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityProvider.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityProvider proto.InternalMessageInfo

func (m *IdentityProvider) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *IdentityProvider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListIdentityProvidersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIdentityProvidersRequest) Reset()         { *m = ListIdentityProvidersRequest{} }
func (m *ListIdentityProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*ListIdentityProvidersRequest) ProtoMessage()    {}
func (*ListIdentityProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{1}
}
func (m *ListIdentityProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIdentityProvidersRequest.Unmarshal(m, b)
}
func (m *ListIdentityProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIdentityProvidersRequest.Marshal(b, m, deterministic)
}
func (dst *ListIdentityProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIdentityProvidersRequest.Merge(dst, src)
}
func (m *ListIdentityProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_ListIdentityProvidersRequest.Size(m)
}
func (m *ListIdentityProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIdentityProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIdentityProvidersRequest proto.InternalMessageInfo

type ListIdentityProvidersResponse struct {
	IdentityProviders    []*IdentityProvider `protobuf:"bytes,1,rep,name=identityProviders,proto3" json:"identityProviders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListIdentityProvidersResponse) Reset()         { *m = ListIdentityProvidersResponse{} }
func (m *ListIdentityProvidersResponse) String() string { return proto.CompactTextString(m) }
func (*ListIdentityProvidersResponse) ProtoMessage()    {}
func (*ListIdentityProvidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{2}
}
func (m *ListIdentityProvidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIdentityProvidersResponse.Unmarshal(m, b)
}
func (m *ListIdentityProvidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIdentityProvidersResponse.Marshal(b, m, deterministic)
}
func (dst *ListIdentityProvidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIdentityProvidersResponse.Merge(dst, src)
}
func (m *ListIdentityProvidersResponse) XXX_Size() int {
	return xxx_messageInfo_ListIdentityProvidersResponse.Size(m)
}
func (m *ListIdentityProvidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIdentityProvidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListIdentityProvidersResponse proto.InternalMessageInfo

func (m *ListIdentityProvidersResponse) GetIdentityProviders() []*IdentityProvider {
	if m != nil {
		return m.IdentityProviders
	}
	return nil
}

type AddIdentityProviderRequest struct {
	IdentityProviderUrl  string   `protobuf:"bytes,1,opt,name=identityProviderUrl,proto3" json:"identityProviderUrl,omitempty"`
	EmailOrPhone         string   `protobuf:"bytes,2,opt,name=emailOrPhone,proto3" json:"emailOrPhone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIdentityProviderRequest) Reset()         { *m = AddIdentityProviderRequest{} }
func (m *AddIdentityProviderRequest) String() string { return proto.CompactTextString(m) }
func (*AddIdentityProviderRequest) ProtoMessage()    {}
func (*AddIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{3}
}
func (m *AddIdentityProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIdentityProviderRequest.Unmarshal(m, b)
}
func (m *AddIdentityProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIdentityProviderRequest.Marshal(b, m, deterministic)
}
func (dst *AddIdentityProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIdentityProviderRequest.Merge(dst, src)
}
func (m *AddIdentityProviderRequest) XXX_Size() int {
	return xxx_messageInfo_AddIdentityProviderRequest.Size(m)
}
func (m *AddIdentityProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIdentityProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddIdentityProviderRequest proto.InternalMessageInfo

func (m *AddIdentityProviderRequest) GetIdentityProviderUrl() string {
	if m != nil {
		return m.IdentityProviderUrl
	}
	return ""
}

func (m *AddIdentityProviderRequest) GetEmailOrPhone() string {
	if m != nil {
		return m.EmailOrPhone
	}
	return ""
}

type AddIdentityProviderResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	IdentityProviderId   string   `protobuf:"bytes,2,opt,name=identityProviderId,proto3" json:"identityProviderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddIdentityProviderResponse) Reset()         { *m = AddIdentityProviderResponse{} }
func (m *AddIdentityProviderResponse) String() string { return proto.CompactTextString(m) }
func (*AddIdentityProviderResponse) ProtoMessage()    {}
func (*AddIdentityProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{4}
}
func (m *AddIdentityProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddIdentityProviderResponse.Unmarshal(m, b)
}
func (m *AddIdentityProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddIdentityProviderResponse.Marshal(b, m, deterministic)
}
func (dst *AddIdentityProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddIdentityProviderResponse.Merge(dst, src)
}
func (m *AddIdentityProviderResponse) XXX_Size() int {
	return xxx_messageInfo_AddIdentityProviderResponse.Size(m)
}
func (m *AddIdentityProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddIdentityProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddIdentityProviderResponse proto.InternalMessageInfo

func (m *AddIdentityProviderResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *AddIdentityProviderResponse) GetIdentityProviderId() string {
	if m != nil {
		return m.IdentityProviderId
	}
	return ""
}

type ConfirmIdentityProviderRequest struct {
	IdentityProviderUrl  string   `protobuf:"bytes,1,opt,name=identityProviderUrl,proto3" json:"identityProviderUrl,omitempty"`
	IdentityProviderId   string   `protobuf:"bytes,2,opt,name=identityProviderId,proto3" json:"identityProviderId,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,3,opt,name=confirmationCode,proto3" json:"confirmationCode,omitempty"`
	ProxyName            string   `protobuf:"bytes,4,opt,name=proxyName,proto3" json:"proxyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmIdentityProviderRequest) Reset()         { *m = ConfirmIdentityProviderRequest{} }
func (m *ConfirmIdentityProviderRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmIdentityProviderRequest) ProtoMessage()    {}
func (*ConfirmIdentityProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{5}
}
func (m *ConfirmIdentityProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmIdentityProviderRequest.Unmarshal(m, b)
}
func (m *ConfirmIdentityProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmIdentityProviderRequest.Marshal(b, m, deterministic)
}
func (dst *ConfirmIdentityProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmIdentityProviderRequest.Merge(dst, src)
}
func (m *ConfirmIdentityProviderRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmIdentityProviderRequest.Size(m)
}
func (m *ConfirmIdentityProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmIdentityProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmIdentityProviderRequest proto.InternalMessageInfo

func (m *ConfirmIdentityProviderRequest) GetIdentityProviderUrl() string {
	if m != nil {
		return m.IdentityProviderUrl
	}
	return ""
}

func (m *ConfirmIdentityProviderRequest) GetIdentityProviderId() string {
	if m != nil {
		return m.IdentityProviderId
	}
	return ""
}

func (m *ConfirmIdentityProviderRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

func (m *ConfirmIdentityProviderRequest) GetProxyName() string {
	if m != nil {
		return m.ProxyName
	}
	return ""
}

type ConfirmIdentityProviderResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmIdentityProviderResponse) Reset()         { *m = ConfirmIdentityProviderResponse{} }
func (m *ConfirmIdentityProviderResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmIdentityProviderResponse) ProtoMessage()    {}
func (*ConfirmIdentityProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{6}
}
func (m *ConfirmIdentityProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmIdentityProviderResponse.Unmarshal(m, b)
}
func (m *ConfirmIdentityProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmIdentityProviderResponse.Marshal(b, m, deterministic)
}
func (dst *ConfirmIdentityProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmIdentityProviderResponse.Merge(dst, src)
}
func (m *ConfirmIdentityProviderResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmIdentityProviderResponse.Size(m)
}
func (m *ConfirmIdentityProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmIdentityProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmIdentityProviderResponse proto.InternalMessageInfo

func (m *ConfirmIdentityProviderResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type GetWalletsAndServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletsAndServicesRequest) Reset()         { *m = GetWalletsAndServicesRequest{} }
func (m *GetWalletsAndServicesRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletsAndServicesRequest) ProtoMessage()    {}
func (*GetWalletsAndServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{7}
}
func (m *GetWalletsAndServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletsAndServicesRequest.Unmarshal(m, b)
}
func (m *GetWalletsAndServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletsAndServicesRequest.Marshal(b, m, deterministic)
}
func (dst *GetWalletsAndServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletsAndServicesRequest.Merge(dst, src)
}
func (m *GetWalletsAndServicesRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletsAndServicesRequest.Size(m)
}
func (m *GetWalletsAndServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletsAndServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletsAndServicesRequest proto.InternalMessageInfo

type GetWalletsAndServicesResponse struct {
	DataForWallet        []string `protobuf:"bytes,1,rep,name=dataForWallet,proto3" json:"dataForWallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletsAndServicesResponse) Reset()         { *m = GetWalletsAndServicesResponse{} }
func (m *GetWalletsAndServicesResponse) String() string { return proto.CompactTextString(m) }
func (*GetWalletsAndServicesResponse) ProtoMessage()    {}
func (*GetWalletsAndServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{8}
}
func (m *GetWalletsAndServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletsAndServicesResponse.Unmarshal(m, b)
}
func (m *GetWalletsAndServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletsAndServicesResponse.Marshal(b, m, deterministic)
}
func (dst *GetWalletsAndServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletsAndServicesResponse.Merge(dst, src)
}
func (m *GetWalletsAndServicesResponse) XXX_Size() int {
	return xxx_messageInfo_GetWalletsAndServicesResponse.Size(m)
}
func (m *GetWalletsAndServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletsAndServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletsAndServicesResponse proto.InternalMessageInfo

func (m *GetWalletsAndServicesResponse) GetDataForWallet() []string {
	if m != nil {
		return m.DataForWallet
	}
	return nil
}

type GetActiveTokensRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActiveTokensRequest) Reset()         { *m = GetActiveTokensRequest{} }
func (m *GetActiveTokensRequest) String() string { return proto.CompactTextString(m) }
func (*GetActiveTokensRequest) ProtoMessage()    {}
func (*GetActiveTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{9}
}
func (m *GetActiveTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActiveTokensRequest.Unmarshal(m, b)
}
func (m *GetActiveTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActiveTokensRequest.Marshal(b, m, deterministic)
}
func (dst *GetActiveTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActiveTokensRequest.Merge(dst, src)
}
func (m *GetActiveTokensRequest) XXX_Size() int {
	return xxx_messageInfo_GetActiveTokensRequest.Size(m)
}
func (m *GetActiveTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActiveTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActiveTokensRequest proto.InternalMessageInfo

type GetActiveTokensResponse struct {
	DataForWallet        []string `protobuf:"bytes,1,rep,name=dataForWallet,proto3" json:"dataForWallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActiveTokensResponse) Reset()         { *m = GetActiveTokensResponse{} }
func (m *GetActiveTokensResponse) String() string { return proto.CompactTextString(m) }
func (*GetActiveTokensResponse) ProtoMessage()    {}
func (*GetActiveTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_1a2019b4e1d26df4, []int{10}
}
func (m *GetActiveTokensResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActiveTokensResponse.Unmarshal(m, b)
}
func (m *GetActiveTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActiveTokensResponse.Marshal(b, m, deterministic)
}
func (dst *GetActiveTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActiveTokensResponse.Merge(dst, src)
}
func (m *GetActiveTokensResponse) XXX_Size() int {
	return xxx_messageInfo_GetActiveTokensResponse.Size(m)
}
func (m *GetActiveTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActiveTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActiveTokensResponse proto.InternalMessageInfo

func (m *GetActiveTokensResponse) GetDataForWallet() []string {
	if m != nil {
		return m.DataForWallet
	}
	return nil
}

func init() {
	proto.RegisterType((*IdentityProvider)(nil), "api.IdentityProvider")
	proto.RegisterType((*ListIdentityProvidersRequest)(nil), "api.ListIdentityProvidersRequest")
	proto.RegisterType((*ListIdentityProvidersResponse)(nil), "api.ListIdentityProvidersResponse")
	proto.RegisterType((*AddIdentityProviderRequest)(nil), "api.AddIdentityProviderRequest")
	proto.RegisterType((*AddIdentityProviderResponse)(nil), "api.AddIdentityProviderResponse")
	proto.RegisterType((*ConfirmIdentityProviderRequest)(nil), "api.ConfirmIdentityProviderRequest")
	proto.RegisterType((*ConfirmIdentityProviderResponse)(nil), "api.ConfirmIdentityProviderResponse")
	proto.RegisterType((*GetWalletsAndServicesRequest)(nil), "api.GetWalletsAndServicesRequest")
	proto.RegisterType((*GetWalletsAndServicesResponse)(nil), "api.GetWalletsAndServicesResponse")
	proto.RegisterType((*GetActiveTokensRequest)(nil), "api.GetActiveTokensRequest")
	proto.RegisterType((*GetActiveTokensResponse)(nil), "api.GetActiveTokensResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProxyAdminClient is the client API for ProxyAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyAdminClient interface {
	ListIdentityProviders(ctx context.Context, in *ListIdentityProvidersRequest, opts ...grpc.CallOption) (*ListIdentityProvidersResponse, error)
	AddIdentityProvider(ctx context.Context, in *AddIdentityProviderRequest, opts ...grpc.CallOption) (*AddIdentityProviderResponse, error)
	ConfirmIdentityProvider(ctx context.Context, in *ConfirmIdentityProviderRequest, opts ...grpc.CallOption) (*ConfirmIdentityProviderResponse, error)
	GetWalletsAndServices(ctx context.Context, in *GetWalletsAndServicesRequest, opts ...grpc.CallOption) (*GetWalletsAndServicesResponse, error)
	GetActiveTokens(ctx context.Context, in *GetActiveTokensRequest, opts ...grpc.CallOption) (*GetActiveTokensResponse, error)
}

type proxyAdminClient struct {
	cc *grpc.ClientConn
}

func NewProxyAdminClient(cc *grpc.ClientConn) ProxyAdminClient {
	return &proxyAdminClient{cc}
}

func (c *proxyAdminClient) ListIdentityProviders(ctx context.Context, in *ListIdentityProvidersRequest, opts ...grpc.CallOption) (*ListIdentityProvidersResponse, error) {
	out := new(ListIdentityProvidersResponse)
	err := c.cc.Invoke(ctx, "/api.ProxyAdmin/listIdentityProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) AddIdentityProvider(ctx context.Context, in *AddIdentityProviderRequest, opts ...grpc.CallOption) (*AddIdentityProviderResponse, error) {
	out := new(AddIdentityProviderResponse)
	err := c.cc.Invoke(ctx, "/api.ProxyAdmin/addIdentityProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) ConfirmIdentityProvider(ctx context.Context, in *ConfirmIdentityProviderRequest, opts ...grpc.CallOption) (*ConfirmIdentityProviderResponse, error) {
	out := new(ConfirmIdentityProviderResponse)
	err := c.cc.Invoke(ctx, "/api.ProxyAdmin/confirmIdentityProvider", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetWalletsAndServices(ctx context.Context, in *GetWalletsAndServicesRequest, opts ...grpc.CallOption) (*GetWalletsAndServicesResponse, error) {
	out := new(GetWalletsAndServicesResponse)
	err := c.cc.Invoke(ctx, "/api.ProxyAdmin/getWalletsAndServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyAdminClient) GetActiveTokens(ctx context.Context, in *GetActiveTokensRequest, opts ...grpc.CallOption) (*GetActiveTokensResponse, error) {
	out := new(GetActiveTokensResponse)
	err := c.cc.Invoke(ctx, "/api.ProxyAdmin/getActiveTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyAdminServer is the server API for ProxyAdmin service.
type ProxyAdminServer interface {
	ListIdentityProviders(context.Context, *ListIdentityProvidersRequest) (*ListIdentityProvidersResponse, error)
	AddIdentityProvider(context.Context, *AddIdentityProviderRequest) (*AddIdentityProviderResponse, error)
	ConfirmIdentityProvider(context.Context, *ConfirmIdentityProviderRequest) (*ConfirmIdentityProviderResponse, error)
	GetWalletsAndServices(context.Context, *GetWalletsAndServicesRequest) (*GetWalletsAndServicesResponse, error)
	GetActiveTokens(context.Context, *GetActiveTokensRequest) (*GetActiveTokensResponse, error)
}

func RegisterProxyAdminServer(s *grpc.Server, srv ProxyAdminServer) {
	s.RegisterService(&_ProxyAdmin_serviceDesc, srv)
}

func _ProxyAdmin_ListIdentityProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentityProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).ListIdentityProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ProxyAdmin/ListIdentityProviders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).ListIdentityProviders(ctx, req.(*ListIdentityProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_AddIdentityProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIdentityProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).AddIdentityProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ProxyAdmin/AddIdentityProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).AddIdentityProvider(ctx, req.(*AddIdentityProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_ConfirmIdentityProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmIdentityProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).ConfirmIdentityProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ProxyAdmin/ConfirmIdentityProvider",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).ConfirmIdentityProvider(ctx, req.(*ConfirmIdentityProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetWalletsAndServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletsAndServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetWalletsAndServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ProxyAdmin/GetWalletsAndServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetWalletsAndServices(ctx, req.(*GetWalletsAndServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyAdmin_GetActiveTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyAdminServer).GetActiveTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ProxyAdmin/GetActiveTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyAdminServer).GetActiveTokens(ctx, req.(*GetActiveTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProxyAdmin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ProxyAdmin",
	HandlerType: (*ProxyAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "listIdentityProviders",
			Handler:    _ProxyAdmin_ListIdentityProviders_Handler,
		},
		{
			MethodName: "addIdentityProvider",
			Handler:    _ProxyAdmin_AddIdentityProvider_Handler,
		},
		{
			MethodName: "confirmIdentityProvider",
			Handler:    _ProxyAdmin_ConfirmIdentityProvider_Handler,
		},
		{
			MethodName: "getWalletsAndServices",
			Handler:    _ProxyAdmin_GetWalletsAndServices_Handler,
		},
		{
			MethodName: "getActiveTokens",
			Handler:    _ProxyAdmin_GetActiveTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_1a2019b4e1d26df4) }

var fileDescriptor_api_1a2019b4e1d26df4 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0x26, 0x59, 0x11, 0x73, 0xfc, 0x8b, 0x53, 0x62, 0x97, 0x6d, 0xda, 0xc6, 0xb1, 0x17, 0xc5,
	0x8b, 0x54, 0xaa, 0xb7, 0x22, 0x21, 0x68, 0x29, 0x14, 0x0d, 0x51, 0xd1, 0xab, 0xc2, 0x98, 0x39,
	0xc6, 0x83, 0x9b, 0x99, 0x75, 0x76, 0x1a, 0xec, 0x3b, 0xfa, 0x04, 0x3e, 0x8d, 0x64, 0x76, 0x1a,
	0xc9, 0xee, 0xec, 0x4a, 0xa1, 0x77, 0xb3, 0xe7, 0xfb, 0xce, 0xff, 0x77, 0x16, 0x3a, 0x22, 0xa3,
	0x61, 0x66, 0xb4, 0xd5, 0x2c, 0x12, 0x19, 0x25, 0xfd, 0xb9, 0xd6, 0xf3, 0x14, 0x8f, 0x44, 0x46,
	0x47, 0x42, 0x29, 0x6d, 0x85, 0x25, 0xad, 0xf2, 0x82, 0xc2, 0x5f, 0x42, 0xf7, 0x54, 0xa2, 0xb2,
	0x64, 0x2f, 0x27, 0x46, 0x2f, 0x49, 0xa2, 0x61, 0x5d, 0x88, 0x2e, 0x4c, 0x1a, 0xb7, 0x06, 0xad,
	0xc3, 0xce, 0x74, 0xf5, 0x64, 0x0f, 0xa0, 0x4d, 0x32, 0x6e, 0x3b, 0x43, 0x9b, 0x24, 0xdf, 0x83,
	0xfe, 0x19, 0xe5, 0xb6, 0xec, 0x99, 0x4f, 0xf1, 0xe7, 0x05, 0xe6, 0x96, 0x4b, 0xd8, 0xad, 0xc1,
	0xf3, 0x4c, 0xab, 0x1c, 0xd9, 0x18, 0x1e, 0x51, 0x19, 0x8c, 0x5b, 0x83, 0xe8, 0xf0, 0xee, 0x71,
	0x6f, 0xb8, 0x6a, 0xa0, 0xec, 0x3a, 0xad, 0xf2, 0xb9, 0x81, 0x64, 0x24, 0x65, 0x85, 0x59, 0xd4,
	0xc0, 0x9e, 0xc3, 0x56, 0xd9, 0xe5, 0xd3, 0xba, 0xab, 0x10, 0xc4, 0x38, 0xdc, 0xc3, 0x85, 0xa0,
	0xf4, 0xbd, 0x99, 0x7c, 0xd7, 0x0a, 0x7d, 0xbf, 0x1b, 0x36, 0x4e, 0xb0, 0x13, 0xcc, 0xe9, 0xfb,
	0x4a, 0xe0, 0x8e, 0xf1, 0x6f, 0x9f, 0x69, 0xfd, 0xcd, 0x86, 0xc0, 0xca, 0x59, 0x4f, 0xaf, 0x86,
	0x1a, 0x40, 0xf8, 0xef, 0x16, 0xec, 0x8d, 0xb5, 0xfa, 0x46, 0x66, 0x71, 0x73, 0x3d, 0x5e, 0xb3,
	0x08, 0xf6, 0x0c, 0xba, 0xb3, 0xa2, 0x06, 0x27, 0x9b, 0xb1, 0x96, 0x18, 0x47, 0x8e, 0x5d, 0xb1,
	0xb3, 0x3e, 0x74, 0x32, 0xa3, 0x7f, 0x5d, 0xbe, 0x13, 0x0b, 0x8c, 0x6f, 0x39, 0xd2, 0x3f, 0x03,
	0x7f, 0x05, 0xfb, 0xb5, 0xdd, 0xfc, 0x7f, 0x7a, 0x2b, 0xc9, 0x9d, 0xa0, 0xfd, 0x2c, 0xd2, 0x14,
	0x6d, 0x3e, 0x52, 0xf2, 0x03, 0x9a, 0x25, 0xcd, 0x70, 0x2d, 0xb9, 0x37, 0xb0, 0x5b, 0x83, 0xfb,
	0xe0, 0x07, 0x70, 0x5f, 0x0a, 0x2b, 0xde, 0x6a, 0x53, 0x90, 0x9c, 0xdc, 0x3a, 0xd3, 0x4d, 0x23,
	0x8f, 0xe1, 0xf1, 0x09, 0xda, 0xd1, 0xcc, 0xd2, 0x12, 0x3f, 0xea, 0x1f, 0xa8, 0xd6, 0x09, 0x5e,
	0xc3, 0x76, 0x05, 0xb9, 0x4e, 0xe8, 0xe3, 0x3f, 0x11, 0xc0, 0x64, 0x35, 0x8e, 0x91, 0x5c, 0x90,
	0x62, 0xe7, 0xd0, 0x4b, 0x43, 0x37, 0xc2, 0x9e, 0xb8, 0x03, 0x68, 0xba, 0xaf, 0x84, 0x37, 0x51,
	0x7c, 0x51, 0x5f, 0x60, 0x4b, 0x54, 0x95, 0xca, 0xf6, 0x9d, 0x6b, 0xfd, 0xdd, 0x24, 0x83, 0x7a,
	0x82, 0x8f, 0x2c, 0x61, 0x7b, 0x16, 0xde, 0x24, 0x7b, 0xea, 0x9c, 0x9b, 0x55, 0x9b, 0x1c, 0x34,
	0x93, 0x7c, 0x96, 0x73, 0xe8, 0xcd, 0x43, 0x0b, 0xf5, 0xf3, 0x69, 0x12, 0x83, 0x9f, 0x4f, 0xb3,
	0x1e, 0xce, 0xe0, 0xe1, 0x7c, 0x73, 0x9f, 0x6c, 0xe7, 0xca, 0x2d, 0xb0, 0xff, 0xa4, 0x1f, 0x06,
	0x8b, 0x68, 0x5f, 0x6f, 0xbb, 0xdf, 0xe9, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x6f,
	0x2d, 0xe2, 0x7e, 0x05, 0x00, 0x00,
}
